version: "3.4"

services:
  mongo:
    image: mongo
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./database/mongo:/usr/local/sampleCollections
    working_dir: /usr/local/sampleCollections

  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  api:
    image: node:16-alpine3.11
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URL: "mongodb://root:password@mongo:27017/app"
      DATABASE_URL: "postgres://root:password@db:5432/app"
    volumes:
      - ./api:/home/node/app
    depends_on:
      - mongo
      - postgres
    working_dir: /home/node/app
    command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"

  backoffice:
    image: node:16-alpine3.11
    ports:
      - 3001:3000
    environment:
      API_URL: http://localhost:3000
      PSP_URL: http://localhost:3003
      SCRAPPER_URL: http://localhost:3004
    depends_on:
      - api
    volumes:
      - ./backoffice:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"

  site_marchand:
    image: node:16-alpine3.11
    ports:
      - 3002:3000
    depends_on:
      - api
    environment:
      BACKOFFICE_URL: http://localhost:3001
    volumes:
      - ./site_marchand:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"

  psp:
    image: node:16-alpine3.11
    ports:
      - 3003:3000
    environment:
      API_URL: http://localhost:3000
    depends_on:
      - api
    volumes:
      - ./psp:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"

  scrapper:
    image: node:16-alpine3.11
    ports:
      - 3004:3000
    depends_on:
      - api
    volumes:
      - ./scrapper:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"

volumes:
  db-data: {}
